/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DownloadDialog.java
 *
 * Created on 14 Nov, 2010, 12:42:50 AM
 */

package net.sf.jsharing.boundary;

import javax.swing.JPanel;
import net.sf.jsharing.components.SavedIPInfo;
import net.sf.jsharing.components.UsefulMethods;

/**
 *
 * @author Pratik
 */
public class UploadDialog extends javax.swing.JDialog {
    private static UploadDialog dd;

    /** Creates new form DownloadDialog */
    private UploadDialog(java.awt.Frame parent) {
        super(parent, false);
        initComponents();

        this.setLocationRelativeTo(parent);
    }

    public static UploadDialog getUD() {
        if(dd == null)
            dd = new UploadDialog(null);
        return dd;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Upload Dialog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void addNewUploadForm(SavedIPInfo sip) {
        if(!MainWindow.mw.isServerRunning()) {
            return;
        }

        if(sip == null) {
            sip = new SavedIPInfo();
            sip.setIp(UsefulMethods.LOCAL_HOST_IP);
            sip.setPort(UsefulMethods.getPortNumber());
        }

        UploadFormPanel ufp = new UploadFormPanel(sip);
        String tabName = "New";
        if(!(sip.getIp().equals(UsefulMethods.LOCAL_HOST_IP) && (sip.getName() == null)))
            tabName = UsefulMethods.getShortNameOfIP(sip.getIp());

        this.jTabbedPane1.addTab(tabName, ufp);
        this.jTabbedPane1.setSelectedComponent(ufp);

        showDialog();
    }

    public void removePanel(JPanel p) {
        jTabbedPane1.remove(p);
        closingLogic();
    }

    public void focusOnPanel(JPanel p) {
        jTabbedPane1.setSelectedComponent(p);
    }

    private void closingLogic() {
        if(jTabbedPane1.getTabCount() == 0)
            closeDialog();
    }

    public void showDialog() {
        if(!this.isVisible())
            this.setVisible(true);
    }

    public void closeDialog() {
        if(this.isVisible())
            this.setVisible(false);
    }
}
